### ISSUE TITLE
AutoLevel Config for NR Common Config

### ISSUE THREAD

**Issue by mdwhitten** [heyItsDale/rf-adv-reference-design-libraries-csharp#1]
Hey @heyItsDale ,

If you look at [the WLAN CommonConfig](https://github.com/heyItsDale/rf-adv-reference-design-libraries-csharp/blob/master/Source/SA/RFmx%20WLAN/RFmxWLAN.cs#L166) function, it has an additional input for AutoLevel config. This is useful in automation so that we don't have to manually calculate the ref level. Is this something you could add to the Common Config?

**Comment by mdwhitten** [comment]
Or is there a reason it should be excluded?

**Comment by heyItsDale** [comment]
yeah I can add that
